INSERT INTO TBL_SELLER (NAME, GENDER, SALARY, BONUS)
VALUES ('Juliana Oliveira', 'FEMALE', 5200.00, 15);

INSERT INTO TBL_SELLER (NAME, GENDER, SALARY, BONUS)
VALUES ('Carlos Henrique', 'MALE', 3800.50, 10);

INSERT INTO TBL_SELLER (NAME, GENDER, SALARY, BONUS)
VALUES ('Mariana Souza', 'FEMALE', 4500.00, 20);